[project]
name = "guidami-ai-patente"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "httpx>=0.28.1",
    "lxml>=6.1.1",
]

[project.scripts]
scrape-codice = "scrapers.normattiva:main_cds"
scrape-cap    = "scrapers.normattiva:main_cap"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
