from pydantic import BaseModel


class QuizMetadata(BaseModel):
    """Regulatory metadata of a quiz bank sub-question.

    Generated by an LLM and used as a retrieval bridge to `knowledge_chunks`.
    Transient ingestion model: not persisted as-is, flattened onto `QuizQuestion`
    at the entity boundary (see `QuizMapper.from_embedded_to_quiz_question`).

    Attributes:
        core_concepts: General regulatory concepts.
        exact_keywords: Exact keywords or technical terms from the Codice della Strada.
        vector_search_queries: Phrases for semantic search in the CdS text.
        rule_explanation: Brief explanation of the regulatory principle.
    """

    core_concepts: list[str]
    exact_keywords: list[str]
    vector_search_queries: list[str]
    rule_explanation: str

    @property
    def embedded_text(self) -> str:
        """Text to use for computing the embedding (satisfies `Embeddable` via duck typing)."""
        return "\n".join(self.vector_search_queries)
