from pydantic import BaseModel, Field


class EnrichedArticleModel(BaseModel):
    """Article with per-comma contexts generated by the LLM (enriched layer).

    Self-contained: does not depend on `ParsedArticleModel` — fields are
    replicated to keep `commons` independent from the ingestor.
    """

    number: str
    title: str
    text: str
    paragraphs: list[str]
    url: str
    scraped_at: str
    repealed: bool
    contexts: dict[int, str] = Field(default_factory=dict)
