from pydantic import BaseModel


class ArticleCommaEntity(BaseModel):
    """Row of the `article_commas` table (see db/init.sql).

    `article_id` is included, unlike DB-generated id columns, because it is a
    caller-supplied foreign key value rather than a column generated by the
    database on insert.
    """

    article_id: int
    comma_number: str
    position: int
    text: str
    is_repealed: bool
    embedding: list[float] | None
