import asyncio
import logging
from collections.abc import Iterable

from commons.use_cases import AsyncUseCase
from commons.utils import deduplicate
from guidami_ai_patente_ingestor.agents import NormReferenceDescriberAgent
from guidami_ai_patente_ingestor.agents.dto.norm_reference_describer import (
    NormReferenceDescriberResponse,
)
from guidami_ai_patente_ingestor.agents.mappers import NormReferenceDescriberMapper
from guidami_ai_patente_ingestor.models.quiz import EnrichedQuizModel

logger = logging.getLogger(__name__)

_DedupeKey = tuple[str, str, bool, str | None]  # (topic, text, correct_answer, image_filename)


def _make_key(q: EnrichedQuizModel) -> _DedupeKey:
    return (q.topic, q.text, q.correct_answer, q.image)


class NormReferenceEnricher(AsyncUseCase[Iterable[EnrichedQuizModel], list[EnrichedQuizModel]]):
    """Enriches sub-questions with norm metadata generated by the LLM.

    The dedup key is `(topic, text, correct_answer, image_filename)`: exact duplicates get a
    single agent call; the result is propagated to all rows sharing the same key. Unique
    calls run concurrently under `asyncio.gather`, bounded by a semaphore.
    """

    def __init__(self, max_concurrency: int, agent: NormReferenceDescriberAgent) -> None:
        """Injects the concurrency limit and the LLM agent for norm metadata generation."""
        # Store the limit, not the Semaphore: an asyncio.Semaphore binds to the loop of its
        # first use; the loop is owned by the caller (AsyncApplyStep), so the semaphore is
        # built per-run in _build_metadata_map.
        self._max_concurrency = max_concurrency
        self._agent = agent

    async def execute(self, request: Iterable[EnrichedQuizModel]) -> list[EnrichedQuizModel]:
        """Runs norm enrichment on every sub-question.

        Args:
            request: Iterable of enriched sub-questions to enrich.

        Returns:
            List of sub-questions with `quiz_metadata` populated where possible.
        """
        questions = list(request)
        metadata_map = await self._build_metadata_map(questions)
        return [self._apply_metadata(q, metadata_map) for q in questions]

    def _apply_metadata(
        self,
        q: EnrichedQuizModel,
        metadata_map: dict[_DedupeKey, NormReferenceDescriberResponse],
    ) -> EnrichedQuizModel:
        response = metadata_map.get(_make_key(q))
        if response is None:
            return q
        return NormReferenceDescriberMapper.from_response_to_enriched_quiz(q, response)

    async def _build_metadata_map(
        self, questions: list[EnrichedQuizModel]
    ) -> dict[_DedupeKey, NormReferenceDescriberResponse]:
        unique = list(deduplicate(questions, key=_make_key))
        logger.info("Generating norm metadata for %d unique question(s)", len(unique))
        semaphore = asyncio.Semaphore(self._max_concurrency)  # bound to this run's loop
        responses = await asyncio.gather(*(self._call_agent(q, semaphore) for q in unique))
        # gather preserves input order -> lockstep zip, no index bookkeeping.
        return {
            _make_key(q): response
            for q, response in zip(unique, responses, strict=True)
            if response is not None
        }

    async def _call_agent(
        self, q: EnrichedQuizModel, semaphore: asyncio.Semaphore
    ) -> NormReferenceDescriberResponse | None:
        try:
            req = NormReferenceDescriberMapper.from_enriched_quiz_to_request(q)
            async with semaphore:
                return await self._agent.run(req, images=())
        except Exception as exc:
            logger.warning(
                "Failed to generate norm reference metadata, skipping: topic=%r text=%r (%s)",
                q.topic,
                q.text,
                exc,
            )
            logger.debug("Norm reference metadata generation failed", exc_info=True)
            return None
